spring:
  application:
    name: coreflow
  datasource:
    url: jdbc:postgresql://localhost:5432/coreflow
    username: coreflow
    password: coreflow
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
  rabbitmq:
    image: rabbitmq:3-management
    container_name: coreflow-rabbitmq
    username: guest
    password: guest
    ports:
      - "5672:5672"   # Port AMQP
      - "15672:15672" # Interface Web Management
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: coreflow-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
